

spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/teste'
    username: root
    password : root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect




